#!/usr/bin/env python3
"""
BIND9 Terraform Configuration Generator

Generates ready-to-use Terraform/OpenTofu configurations for managing
BIND9 DNS servers using the harutyundermenjyan/bind9 provider.

Usage:
    python generate.py                        # Use default config.yaml
    python generate.py -c custom.yaml         # Use custom config
    python generate.py -o ./my-output         # Custom output directory
    python generate.py --dry-run              # Preview without writing
"""

import os
import re
import sys
import argparse
from pathlib import Path
from dataclasses import dataclass, field

import yaml


# =============================================================================
# Data Classes
# =============================================================================

@dataclass
class Server:
    """BIND9 server configuration."""
    name: str
    endpoint: str
    api_key: str
    enabled: bool = True


@dataclass
class AclConfig:
    """ACL configuration."""
    name: str
    entries: list[str]
    comment: str = ""
    servers: list[str] = field(default_factory=list)


@dataclass
class ZoneDefaults:
    """Default values for zone creation."""
    soa_mname: str = "ns1.example.com"
    soa_rname: str = "hostmaster.example.com"
    soa_refresh: int = 3600
    soa_retry: int = 600
    soa_expire: int = 604800
    soa_minimum: int = 86400
    default_ttl: int = 3600
    nameservers: list[str] = field(default_factory=list)
    ns_addresses: dict[str, str] = field(default_factory=dict)
    allow_update: list[str] = field(default_factory=lambda: ["ddns-clients"])
    allow_transfer: list[str] = field(default_factory=lambda: ["trusted-secondaries"])
    allow_query: list[str] = field(default_factory=lambda: ["any"])


@dataclass
class ZoneConfig:
    """Zone configuration."""
    name: str
    servers: list[str] = field(default_factory=list)


@dataclass
class RecordConfig:
    """Record configuration."""
    zone: str
    name: str
    type: str
    ttl: int
    records: list[str]
    servers: list[str] = field(default_factory=list)


# =============================================================================
# Generator
# =============================================================================

class TerraformGenerator:
    """Generates Terraform configurations for BIND9 provider."""

    def __init__(
        self,
        servers: list[Server],
        zone_defaults: ZoneDefaults,
        acls: list[AclConfig],
        zones: list[ZoneConfig],
        records: list[RecordConfig],
        provider_version: str,
        output_dir: str = "./generated",
    ):
        self.servers = [s for s in servers if s.enabled]
        self.zone_defaults = zone_defaults
        self.acls = acls
        self.zones = zones
        self.records = records
        self.provider_version = provider_version
        self.output_dir = Path(output_dir)

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """Convert a name to a valid Terraform identifier."""
        sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        if sanitized and sanitized[0].isdigit():
            sanitized = "_" + sanitized
        return sanitized

    # =========================================================================
    # File Generators
    # =========================================================================

    def generate_versions_tf(self) -> str:
        return f'''# ==============================================================================
# Terraform/OpenTofu Configuration
# ==============================================================================
# Generated by bind9-terraform-generator

terraform {{
  required_version = ">= 1.0"

  required_providers {{
    bind9 = {{
      source  = "harutyundermenjyan/bind9"
      version = "{self.provider_version}"
    }}
  }}
}}
'''

    def generate_variables_tf(self) -> str:
        return '''# ==============================================================================
# Variables
# ==============================================================================
# Generated by bind9-terraform-generator

variable "servers" {
  description = "DNS servers configuration"
  type = map(object({
    endpoint = string
    api_key  = string
    enabled  = bool
  }))
  sensitive = true
}
'''

    def generate_tfvars(self) -> str:
        lines = [
            '# ==============================================================================',
            '# Server Credentials',
            '# ==============================================================================',
            '# Generated by bind9-terraform-generator',
            '# Contains sensitive values - DO NOT COMMIT TO GIT',
            '',
            'servers = {',
        ]
        for server in self.servers:
            lines.extend([
                f'  "{server.name}" = {{',
                f'    endpoint = "{server.endpoint}"',
                f'    api_key  = "{server.api_key}"',
                f'    enabled  = {str(server.enabled).lower()}',
                '  }',
            ])
        lines.append('}')
        return '\n'.join(lines)

    def generate_acls_tf(self) -> str:
        lines = [
            '# ==============================================================================',
            '# ACLs - Access Control Lists',
            '# ==============================================================================',
            '# Generated by bind9-terraform-generator',
            '# servers = []         -> ALL servers (default)',
            '# servers = ["dns1"]   -> only dns1',
            '# ==============================================================================',
            '',
            'locals {',
            '  acls = {',
        ]
        for acl in self.acls:
            servers_str = ', '.join(f'"{s}"' for s in acl.servers) if acl.servers else ''
            escaped_entries = [e.replace('\\', '\\\\').replace('"', '\\"') for e in acl.entries]
            entries_str = ', '.join(f'"{e}"' for e in escaped_entries)
            lines.append(f'    {self._sanitize_name(acl.name)} = {{')
            lines.append(f'      name    = "{acl.name}"')
            lines.append(f'      entries = [{entries_str}]')
            lines.append(f'      comment = "{acl.comment}"')
            lines.append(f'      servers = [{servers_str}]')
            lines.append('    }')
            lines.append('')
        lines.append('  }')
        lines.append('}')
        return '\n'.join(lines)

    def generate_zones_tf(self) -> str:
        lines = [
            '# ==============================================================================',
            '# Zones Configuration',
            '# ==============================================================================',
            '# Generated by bind9-terraform-generator',
            '# servers = []         -> ALL servers (default)',
            '# servers = ["dns1"]   -> only dns1',
            '# ==============================================================================',
            '',
            'locals {',
            '  # Default SOA settings',
            '  default_soa = {',
            f'    soa_mname   = "{self.zone_defaults.soa_mname}"',
            f'    soa_rname   = "{self.zone_defaults.soa_rname}"',
            f'    soa_refresh = {self.zone_defaults.soa_refresh}',
            f'    soa_retry   = {self.zone_defaults.soa_retry}',
            f'    soa_expire  = {self.zone_defaults.soa_expire}',
            f'    soa_minimum = {self.zone_defaults.soa_minimum}',
            '  }',
            '',
            '  # Default nameservers',
            '  default_ns = {',
        ]
        if self.zone_defaults.nameservers:
            ns_str = ', '.join(f'"{ns}"' for ns in self.zone_defaults.nameservers)
            lines.append(f'    nameservers = [{ns_str}]')
            lines.append('    ns_addresses = {')
            for ns, ip in self.zone_defaults.ns_addresses.items():
                lines.append(f'      "{ns}" = "{ip}"')
            lines.append('    }')
        else:
            lines.append('    nameservers = []')
            lines.append('    ns_addresses = {}')
        lines.extend([
            '  }',
            '',
            '  zones = {',
        ])
        for zone in self.zones:
            safe_name = self._sanitize_name(zone.name)
            servers_str = ', '.join(f'"{s}"' for s in zone.servers) if zone.servers else ''
            allow_query = ', '.join(f'"{a}"' for a in self.zone_defaults.allow_query)
            allow_transfer = ', '.join(f'"{a}"' for a in self.zone_defaults.allow_transfer)
            allow_update = ', '.join(f'"{a}"' for a in self.zone_defaults.allow_update)
            lines.append(f'    {safe_name} = merge(local.default_soa, local.default_ns, {{')
            lines.append(f'      name           = "{zone.name}"')
            lines.append(f'      type           = "master"')
            lines.append(f'      default_ttl    = {self.zone_defaults.default_ttl}')
            lines.append(f'      allow_query    = [{allow_query}]')
            lines.append(f'      allow_transfer = [{allow_transfer}]')
            lines.append(f'      allow_update   = [{allow_update}]')
            lines.append(f'      notify         = true')
            lines.append(f'      servers        = [{servers_str}]')
            lines.append('    })')
            lines.append('')
        lines.append('  }')
        lines.append('}')
        return '\n'.join(lines)

    def generate_records_tf(self) -> str:
        lines = [
            '# ==============================================================================',
            '# Records Configuration',
            '# ==============================================================================',
            '# Generated by bind9-terraform-generator',
            '# servers = []         -> ALL servers (default)',
            '# servers = ["dns1"]   -> only dns1',
            '# ==============================================================================',
            '',
            'locals {',
            '  records = {',
        ]

        # Group records by zone
        zones_records: dict[str, list[RecordConfig]] = {}
        for rec in self.records:
            zones_records.setdefault(rec.zone, []).append(rec)

        for zone_name, zone_records in zones_records.items():
            safe_zone = self._sanitize_name(zone_name)
            lines.append(f'    # Zone: {zone_name}')
            lines.append(f'    {safe_zone} = {{')

            for rec in zone_records:
                safe_name = self._sanitize_name(rec.name) if rec.name != "@" else "apex"
                rec_key = f'{safe_name}_{rec.type}'
                servers_str = ', '.join(f'"{s}"' for s in rec.servers) if rec.servers else ''
                values = []
                for v in sorted(rec.records):
                    escaped = v.replace('\\', '\\\\').replace('"', '\\"')
                    values.append(f'"{escaped}"')
                lines.append(f'      {rec_key} = {{')
                lines.append(f'        name    = "{rec.name}"')
                lines.append(f'        type    = "{rec.type}"')
                lines.append(f'        ttl     = {rec.ttl}')
                lines.append(f'        records = [{", ".join(values)}]')
                lines.append(f'        servers = [{servers_str}]')
                lines.append('      }')

            lines.append('    }')
            lines.append('')

        lines.extend([
            '  }',
            '',
            '  # Flatten records for iteration',
            '  flat_records = merge([',
            '    for zone_key, zone_records in local.records : {',
            '      for rec_key, rec in zone_records :',
            '      "${zone_key}/${rec_key}" => merge(rec, {',
            '        zone_key  = zone_key',
            '        zone_name = local.zones[zone_key].name',
            '      })',
            '    }',
            '  ]...)',
            '}',
        ])
        return '\n'.join(lines)

    def generate_servers_tf(self) -> str:
        lines = [
            '# ==============================================================================',
            '# DNS SERVERS',
            '# ==============================================================================',
            '# Generated by bind9-terraform-generator',
            '#',
            '# To ADD a server:',
            '#   1. Add credentials to terraform.tfvars',
            '#   2. Copy a server block below and replace the server name',
            '#',
            '# To REMOVE a server:',
            '#   1. Remove from terraform.tfvars',
            '#   2. Delete the server block below',
            '# ==============================================================================',
            '',
        ]
        for server in self.servers:
            sname = server.name
            lines.extend([
                '',
                f'# {"=" * 76}',
                f'# {sname.upper()}',
                f'# {"=" * 76}',
                '',
                'provider "bind9" {',
                f'  alias    = "{sname}"',
                f'  endpoint = var.servers["{sname}"].endpoint',
                f'  api_key  = var.servers["{sname}"].api_key',
                '}',
                '',
                'locals {',
                f'  acls_{sname} = {{',
                '    for k, v in local.acls : k => v',
                f'    if var.servers["{sname}"].enabled && (length(v.servers) == 0 || contains(v.servers, "{sname}"))',
                '  }',
                f'  zones_{sname} = {{',
                '    for k, v in local.zones : k => v',
                f'    if var.servers["{sname}"].enabled && (length(v.servers) == 0 || contains(v.servers, "{sname}"))',
                '  }',
                f'  records_{sname} = {{',
                '    for k, v in local.flat_records : k => v',
                f'    if var.servers["{sname}"].enabled && (length(v.servers) == 0 || contains(v.servers, "{sname}"))',
                '  }',
                '}',
                '',
                f'resource "bind9_acl" "{sname}" {{',
                f'  for_each = local.acls_{sname}',
                f'  provider = bind9.{sname}',
                '  name     = each.value.name',
                '  entries  = each.value.entries',
                '  comment  = each.value.comment',
                '}',
                '',
                f'resource "bind9_zone" "{sname}" {{',
                f'  for_each       = local.zones_{sname}',
                f'  provider       = bind9.{sname}',
                f'  depends_on     = [bind9_acl.{sname}]',
                '  name           = each.value.name',
                '  type           = each.value.type',
                '  soa_mname      = each.value.soa_mname',
                '  soa_rname      = each.value.soa_rname',
                '  soa_refresh    = each.value.soa_refresh',
                '  soa_retry      = each.value.soa_retry',
                '  soa_expire     = each.value.soa_expire',
                '  soa_minimum    = each.value.soa_minimum',
                '  default_ttl    = each.value.default_ttl',
                '  nameservers    = each.value.nameservers',
                '  ns_addresses   = each.value.ns_addresses',
                '  allow_query    = each.value.allow_query',
                '  allow_transfer = each.value.allow_transfer',
                '  allow_update   = each.value.allow_update',
                '  notify         = each.value.notify',
                '}',
                '',
                f'resource "bind9_record" "{sname}" {{',
                f'  for_each   = local.records_{sname}',
                f'  provider   = bind9.{sname}',
                f'  depends_on = [bind9_zone.{sname}]',
                '  zone       = each.value.zone_name',
                '  name       = each.value.name',
                '  type       = each.value.type',
                '  ttl        = each.value.ttl',
                '  records    = each.value.records',
                '}',
                '',
                f'output "{sname}_zones" {{',
                f'  value = [for z in bind9_zone.{sname} : z.name]',
                '}',
            ])
        return '\n'.join(lines)

    def generate_gitignore(self) -> str:
        return '''# Terraform
.terraform/
.terraform.lock.hcl
*.tfstate
*.tfstate.*
crash.log
crash.*.log

# Sensitive files
terraform.tfvars
*.tfvars
!*.tfvars.example

# Override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json
'''

    def write_all(self) -> dict:
        """Write all generated files. Returns dict of filename -> content."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        files = {
            "versions.tf": self.generate_versions_tf(),
            "variables.tf": self.generate_variables_tf(),
            "terraform.tfvars": self.generate_tfvars(),
            "acls.tf": self.generate_acls_tf(),
            "zones.tf": self.generate_zones_tf(),
            "records.tf": self.generate_records_tf(),
            "servers.tf": self.generate_servers_tf(),
            ".gitignore": self.generate_gitignore(),
        }

        for filename, content in files.items():
            (self.output_dir / filename).write_text(content)

        return files


# =============================================================================
# Config Loader
# =============================================================================

def load_config(path: str) -> dict:
    """Load configuration from YAML file."""
    config_path = Path(path)
    if not config_path.exists():
        print(f"Error: Config file not found: {path}")
        print("Copy config.yaml.example to config.yaml and edit it.")
        sys.exit(1)
    with open(config_path) as f:
        return yaml.safe_load(f)


def parse_config(cfg: dict) -> tuple:
    """Parse config dict into typed objects."""
    # Provider version
    provider_cfg = cfg.get("provider", {})
    if "version" not in provider_cfg:
        print("Error: provider.version is required in config.yaml")
        sys.exit(1)
    provider_version = provider_cfg["version"]

    # Servers
    servers = []
    for s in cfg.get("servers", []):
        servers.append(Server(
            name=s["name"],
            endpoint=s["endpoint"],
            api_key=s["api_key"],
            enabled=s.get("enabled", True),
        ))
    if not servers:
        print("Error: At least one server is required in config.yaml")
        sys.exit(1)

    # ACLs
    acls = []
    for a in cfg.get("acls", []):
        acls.append(AclConfig(
            name=a["name"],
            entries=a.get("entries", []),
            comment=a.get("comment", ""),
            servers=a.get("servers", []),
        ))

    # Zone defaults
    zd = cfg.get("zone_defaults", {})
    zone_defaults = ZoneDefaults(
        soa_mname=zd.get("soa_mname", "ns1.example.com"),
        soa_rname=zd.get("soa_rname", "hostmaster.example.com"),
        soa_refresh=zd.get("soa_refresh", 3600),
        soa_retry=zd.get("soa_retry", 600),
        soa_expire=zd.get("soa_expire", 604800),
        soa_minimum=zd.get("soa_minimum", 86400),
        default_ttl=zd.get("default_ttl", 3600),
        nameservers=zd.get("nameservers", []),
        ns_addresses=zd.get("ns_addresses", {}),
        allow_update=zd.get("allow_update", ["ddns-clients"]),
        allow_transfer=zd.get("allow_transfer", ["trusted-secondaries"]),
        allow_query=zd.get("allow_query", ["any"]),
    )

    # Zones
    zones = []
    for z in cfg.get("zones", []):
        zones.append(ZoneConfig(
            name=z["name"],
            servers=z.get("servers", []),
        ))

    # Records
    records = []
    for r in cfg.get("records", []):
        records.append(RecordConfig(
            zone=r["zone"],
            name=r["name"],
            type=r["type"],
            ttl=r.get("ttl", zone_defaults.default_ttl),
            records=r["records"],
            servers=r.get("servers", []),
        ))

    output_dir = cfg.get("output", {}).get("directory", "./generated")

    return servers, zone_defaults, acls, zones, records, provider_version, output_dir


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Generate Terraform configurations for BIND9 DNS management",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python generate.py                    Generate using config.yaml
  python generate.py -c custom.yaml     Use custom config file
  python generate.py -o ./my-output     Custom output directory
  python generate.py --dry-run          Preview without writing files
        """,
    )
    parser.add_argument(
        "-c", "--config",
        default="config.yaml",
        help="Path to configuration file (default: config.yaml)",
    )
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output directory (overrides config)",
    )
    parser.add_argument(
        "-n", "--dry-run",
        action="store_true",
        help="Preview what would be generated without writing files",
    )
    args = parser.parse_args()

    print("BIND9 Terraform Configuration Generator")
    print("=" * 40)
    print()

    # Load and parse config
    cfg = load_config(args.config)
    servers, zone_defaults, acls, zones, records, provider_version, output_dir = parse_config(cfg)

    if args.output:
        output_dir = args.output

    enabled_servers = [s for s in servers if s.enabled]
    print(f"Provider version: {provider_version}")
    print(f"Servers: {', '.join(s.name for s in enabled_servers)} ({len(enabled_servers)} total)")
    print(f"ACLs: {len(acls)}")
    print(f"Zones: {len(zones)}")
    print(f"Records: {len(records)}")
    print(f"Output: {output_dir}")
    print()

    if args.dry_run:
        print("DRY RUN - no files will be written")
        print()
        print("Would generate:")
        print(f"  {output_dir}/")
        print(f"  ├── versions.tf")
        print(f"  ├── variables.tf")
        print(f"  ├── acls.tf          ({len(acls)} ACLs)")
        print(f"  ├── zones.tf         ({len(zones)} zones)")
        print(f"  ├── records.tf       ({len(records)} records)")
        print(f"  ├── servers.tf       ({len(enabled_servers)} servers)")
        print(f"  ├── terraform.tfvars")
        print(f"  └── .gitignore")
        return

    # Generate
    generator = TerraformGenerator(
        servers=servers,
        zone_defaults=zone_defaults,
        acls=acls,
        zones=zones,
        records=records,
        provider_version=provider_version,
        output_dir=output_dir,
    )

    files = generator.write_all()

    print("Generated files:")
    for filename in files:
        filepath = Path(output_dir) / filename
        print(f"  {filepath}")

    print()
    print("Next steps:")
    print(f"  1. cd {output_dir}")
    print(f"  2. Review and update terraform.tfvars with your server credentials")
    print(f"  3. tofu init")
    print(f"  4. tofu plan")
    print(f"  5. tofu apply")


if __name__ == "__main__":
    main()
